### ISSUE TITLE
credentials are not passed through from device_manager::devices

### ISSUE THREAD

**Issue by MichalBryxi** [puppetlabs/device_manager#19]
1) Got fresh machine, installed latest 2018.2.x PE
2) Installed this module via: `sudo puppet module install puppetlabs-device_manager`
3) Created classifier group "Cisco ios routers" with "Class: device_manager::devices" and Devices parameter:
```
{"bigip1.example.com":{"type":"cisco_ios","run_interval":30,"credentials":{"address":"10.0.1.245","port":"22","username":"adminFOOO","password":"cisco2600","enable_password":"cisco2600"}}}
```
4) Pinned a node to that group (for simplicity I used the master itself, but don't think that should make any difference)
5) Ran puppet on that node.
6) Got following error:
> Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Parameter Error: either credentials or url must be specified (file: /etc/puppetlabs/code/environments/production/modules/device_manager/manifests/init.pp, line: 31, column: 5) (file: /etc/puppetlabs/code/environments/production/modules/device_manager/manifests/devices.pp, line: 55) on node jbvp4guldxcwtad.delivery.puppetlabs.net

And looks like [devices.pp:55](https://github.com/puppetlabs/device_manager/blob/master/manifests/devices.pp#L55) reads some data from hierra? Can't tell what's wrong / how to fix it. But this was almost pristine machine, so should not be happening?

**Comment by MichalBryxi** [comment]
cc: @DavidS @tphoney

**Comment by MichalBryxi** [comment]
Ok so just debugged this with Dimitri and when we specify `url` parameter, it works. So seems like the module is unable to extract `credentials` parameter from the devices parameter.

**Comment by DavidS** [comment]
Yeah, https://github.com/puppetlabs/device_manager/blob/3f4978c1c0f6b089622f994c728501442cb52822/manifests/devices.pp#L55 is not passing credentials through.
