### ISSUE TITLE
hiera.yaml' has wrong type, unrecognized key 'device_manager::devices'

### ISSUE THREAD

**Issue by vfstaboy** [puppetlabs/device_manager#34]
Trying to get this working using hiera and encryption.  It appears that hiera doesn't recognize "device_manager::devices" key.  I have tried this on PE 2018 and puppetlabs community version 6.

manifests/site.pp
```
node 'agent.example.com' {
  include device_manager::devices
}
```
hiera.yaml
```
---
version: 5
defaults:
  # The default value for "datadir" is "data" under the same directory as the hiera.yaml
  # file (this file)
  # When specifying a datadir, make sure the directory exists.
  # See https://puppet.com/docs/puppet/latest/environments_about.html for further details on environments.
  # datadir: data
  # data_hash: yaml_data
hierarchy:
  - name: "Per-node data (yaml version)"
    path: "nodes/%{::trusted.certname}.yaml"
  - name: "Other YAML hierarchy levels"
    paths:
      - "common.yaml"
  - name: "eyaml"
    lookup_key: eyaml_lookup_key
    paths:
      - "nodes/%{trusted.certname}.eyaml"
      - "common.eyaml"
    options:
      pkcs7_private_key: /etc/puppetlabs/puppet/keys/private_key.pkcs7.pem
      pkcs7_public_key:  /etc/puppetlabs/puppet/keys/public_key.pkcs7.pem
device_manager::devices:
    netscaler-dev-ext-01:
      type:        'netscaler'
      url:         "https://%{netscaler.dev}@netscaler-dev-ext-01.example.com/nitro/v1/"
  
    netscaler-dev-int-01:
      type:        'netscaler'
      url:         "https://%{netscaler.dev}@netscaler-dev-int-01.example.com/nitro/v1/"
```
Running "puppet agent -t" on proxy agent results in the following error:
```
Info: Using configured environment 'dev_netscaler'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, The Lookup Configuration at '/etc/puppetlabs/code/environments/dev_netscaler/hiera.yaml' has wrong type, unrecognized key 'device_manager::devices' (file: /etc/puppetlabs/code/environments/dev_netscaler/manifests/site.pp, line: 2, column: 3) on node agent.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
If the devices are specified in a manifest under the agent node then the device.conf file is created.  However I cannot use encryption.  I have also tried replacing the variables in hiera.yaml with the username and password but still see the same problem.  Am I doing something wrong here?

**Comment by tkishel** [comment]
Yes ...

You are defining the `device_manager::devices` key in hiera.yaml, which is designed to configure Hiera:

https://puppet.com/docs/puppet/5.5/hiera_config_yaml_5.html

Instead, define the key in the `nodes/%{trusted.certname}.eyaml` file where `trusted.certname` is the certname of the puppet agent you would like to configure as a proxy for your netscaler devices.

**Comment by vfstaboy** [comment]
@tkishel Thank you!  This is now creating device.conf on the agent.  I see now that devices need to be defined in hiera backend.  However the variable isn't printing out the decrypted username password.  I'll dig more into eyaml documentation.

**Comment by vfstaboy** [comment]
After researching eyaml today it seems to me that it's not possible to use a variable in the eyaml backend to access the encrypted username password that is also in an eyaml backend.  It seems that I need to enter the string ENC output of eyaml encrypt to the username:password portion of the url.  Is there a cleaner method for doing this rather than inserting the ENC string for every device url to be setup?  If this is something outside the realm of device_manager I can pursue this on ask.puppet.com.  Sorry if this is an obvious method I'm new to puppet.
This is what I have tried and even had the encrypted portion in another eyaml file (common.eyaml)

eyaml edit node.eyaml

```
---
netscalerdev: DEC(1)::PKCS7[<plaintextstring>]!
device_manager::devices:
    netscaler-dev-ext-01:
      type:        'netscaler'
      url:         "https://%{netscalerdev}@netscaler-dev-ext-01.example.com/nitro/v1/"
  
    netscaler-dev-int-01:
      type:        'netscaler'
      url:         "https://%{netscalerdev}@netscaler-dev-int-01.example.com/nitro/v1/"
```
puppet lookup can find the "netscalerdev" key and decrypt no problem but it looks like interpolation doesn't work here because it's like the chicken and the egg syndrome.

**Comment by tkishel** [comment]
Yes, this a pure Hiera question :)

Take a look at the following for the correct format for an interpolated
lookup of one Hiera value in another:

https://puppet.com/docs/puppet/5.5/hiera_merging.html#the-lookup-and-hiera-function

**Comment by vfstaboy** [comment]
That's it! Thank you so much again!  @tkishel

**Comment by tkishel** [comment]
You are welcome!
