### ISSUE TITLE
F5 URL should accept Sensitive data type

### ISSUE THREAD

**Issue by johna-pnap** [puppetlabs/device_manager#54]
F5 URLs should be  Variant\[String, [Sensitive](https://puppet.com/docs/puppet/6.5/lang_data_sensitive.html)\[String\]\] instead of just String.

Currently, this code:

```
$password = Sensitive(lookup('f5::password',))
$url = Sensitive("https://${user}:${password.unwrap}@${host}/")
device_manager { 'my_f5':
  type => 'f5',
  url   => $url
}
```
produces this error:
```
 parameter 'url' expects a String value, got Sensitive[String]
```

**Comment by johna-pnap** [comment]
I guess this is more complicated than I thought.   That simple change leads only to the contents of the file containing "Sensitive [ value redacted ]" instead of the password.

**Comment by DavidS** [comment]
Created https://tickets.puppetlabs.com/browse/MODULES-9461 to track this on our board

**Comment by bastelfreak** [comment]
still important...
