### ISSUE TITLE
Don't expect `puppet device` to run on the puppet master

### ISSUE THREAD

**Issue by JonasVerhofste** [puppetlabs/device_manager#61]
## Describe the Bug
cbe9679717cf9678acfb6b730ec700d7fafe4e14 changed the devices directory to be owned by `$settings::user` and `$settings::group`. i.e.
>Additionally, this changes the owner/group of the `devices` directory
to use the puppetmaster's user/group settings to line up with what
puppet itself forces the permissions of the directory to be.

It is wrong to assume the `puppet device` command is ran on the master, as well as to assume the user on a proxy-agent is the same as the user on the master. 

## Expected Behavior
`${::puppet_settings_confdir}/puppet/devices` should be owned by the user that `puppet agent` is run as

**Comment by tkishel** [comment]
This should be resolved by the merged PR.

**Comment by JonasVerhofste** [comment]
It is indeed.
