### ISSUE TITLE
Need Puppet 7 Compatible Release

### ISSUE THREAD

**Issue by nabber00** [puppetlabs/device_manager#85]
## Use Case
Puppet 7
Currently: Puppet >= 5.5.10 < 7.0.0

## Describe the Solution You Would Like
Test/Develop and publish a new release that is known to be compatible with Puppet 7 with metadata updated accordingly.

## Additional Context
Puppet 7 was first released in November 2020, almost a year ago.  Also device_manager is tagged as a supported module.

**Comment by bastelfreak** [comment]
yes it is still important...

**Comment by david22swan** [comment]
Release has been made, sorry for the wait.
<img width="904" alt="Screen Shot 2022-05-23 at 3 28 16 PM" src="https://user-images.githubusercontent.com/21069923/169842180-aac68fa3-e979-459f-aca9-863580adba89.png">
